jobs:
- name: development
  plan:
  - get: dataworks-analytical-frontend-service
    trigger: true
  - .: (( inject meta.plan.create-aws-profiles ))
    params:
      AWS_ACC: ((aws_account.management-dev))
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
  - .: (( inject meta.plan.terraform-output ))
  # The following task should be done BEFORE the terraform apply
  # as it will overwrite app client settings
  - .: (( inject meta.plan.set-cognito-client-options ))
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
