jobs:
- name: integration
  plan:
  - get: dataworks-analytical-frontend-service
    trigger: true
    passed:
      - qa
  - get: custom-auth-lambda-release
    version: { tag: '0.0.13' }
    trigger: true
    passed:
      - qa
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: integration
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: integration

