jobs:
  - name: preprod
    plan:
      - get: dataworks-analytical-frontend-service
        trigger: true
        passed:
          - qa
      - .: (( inject meta.plan.create-aws-profiles ))
        params:
          AWS_ACC: ((aws_account.management))
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-output ))
        params:
          TF_WORKSPACE: preprod
      # The following task should be done BEFORE the terraform apply
      # as it will overwrite app client settings
      - .: (( inject meta.plan.set-cognito-client-options ))
      - .: (( inject meta.plan.terraform-apply ))
        config:
          run:
            dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.terraform-plan ))
        config:
          run:
            dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
        params:
          TF_WORKSPACE: preprod
