jobs:
  - name: production
    plan:
      - get: dataworks-analytical-frontend-service
        trigger: true
        passed:
          - preprod
      - .: (( inject meta.plan.create-aws-profiles ))
        params:
          AWS_ACC: ((aws_account.management))
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
      - .: (( inject meta.plan.terraform-output ))
        params:
          TF_WORKSPACE: production
      - .: (( inject meta.plan.terraform-apply ))
        config:
          run:
            dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
        params:
          TF_WORKSPACE: production
      - .: (( inject meta.plan.terraform-plan ))
        config:
          run:
            dir: 'dataworks-analytical-frontend-service/terraform/deploy/app'
        params:
          TF_WORKSPACE: production
      - .: (( inject meta.plan.set-cognito-client-options ))