jobs:
- name: dataworks-analytical-frontend-service-pr
  plan:
  - get: dataworks-analytical-frontend-service-pr
    trigger: true
    version: every
  - put: dataworks-analytical-frontend-service-pr
    params:
      context: $BUILD_JOB_NAME
      path: dataworks-analytical-frontend-service-pr
      status: pending
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
    input_mapping:
      dataworks-analytical-frontend-service: dataworks-analytical-frontend-service-pr
  - task: terraform-plan-app
    .: (( inject meta.plan.terraform-common-config ))
    config:
      run:
        path: sh
        dir: dataworks-analytical-frontend-service/terraform/deploy/app
        args:
        - -exc
        - |
          cp ../../../../terraform-config/terraform.tf .
          cp ../../../../terraform-config/terraform.tfvars .
          terraform init
          terraform workspace show
          terraform plan -var assume_role=ci
      inputs:
      - name: dataworks-analytical-frontend-service
      - name: terraform-config
    input_mapping:
      dataworks-analytical-frontend-service: dataworks-analytical-frontend-service-pr
    on_failure:
      put: dataworks-analytical-frontend-service-pr
      params:
        context: $BUILD_JOB_NAME
        path: dataworks-analytical-frontend-service-pr
        status: failure
    on_success:
      put: dataworks-analytical-frontend-service-pr
      params:
        context: $BUILD_JOB_NAME
        path: dataworks-analytical-frontend-service-pr
        status: success
