jobs:
- name: qa
  plan:
  - get: analytical-frontend-service
    trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'analytical-frontend-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'analytical-frontend-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: qa
