name: High vulns Snyk PR scan

on: pull_request

env:
  IMAGE_NAME: dwpdigital/analytical-frontend-service

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - run: npm run build
      - run: npm test
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
      # - name: Run Snyk to check image for high vulnerabilities
      #   uses: snyk/actions/docker@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     image: ${{ env.IMAGE_NAME }}
      #     args: --file=Dockerfile --severity-threshold=high --exclude-base-image-vulns --org=dwp-dataworks
